spring.application.name=project
notification.type=sms
#debug=true
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:file:/Users/kumarpriyansh/Documents/java_project/project 2/src/main/java/com/priyansh/code/project/db
#spring.datasource.username=priyansh
#spring.datasource.password=123
#debug=true


